AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*
  RunRailsCops: true

Documentation:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundMethodBody:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false 


Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 105
